version: '3'
services:
  composer:
    image: composer:latest
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    restart: "no"

  php:
    image: php:latest
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app